import { PageHero } from "@/components/quiet-forensics";
const SECTIONS=[
["Submitted content","Free Unicode scanning and supported file inspection run in the browser. Billable text/file sanitation uses an ephemeral server request so authoritative credit reservation and output verification can occur together; raw text, file bytes and filenames are not intentionally persisted. Semantic editing sends submitted prose to the configured model through Vercel AI Gateway only after the user explicitly requests an edit."],
["Accounts and billing","Supabase stores identity/session data. Provenance Cleaner stores credit ledger entries, reservation status, purchase identifiers and bounded operational metadata, but not document bodies or filenames. Stripe receives Checkout/payment information and the minimum purchase identifiers needed for reconciliation."],
["Promotional-credit abuse prevention","After a verified account claims signup credits, the service may retain a keyed, non-reversible HMAC fingerprint of the normalized email solely to prevent repeated promotional claims after account deletion. The fingerprint is not the email address and is not exposed to clients."],
["Deletion and rights","Account deletion is offered only when backend readiness confirms that identity deletion can detach retained accounting records safely. Narrow anti-abuse and payment-reconciliation records may remain when necessary to preserve financial integrity and promotion-abuse controls."],
["Analytics","Product analytics is currently disabled. Any future activation must be cookieless/memoryless, exclude submitted content and filenames, and emit zero events when Do Not Track is enabled."],
] as const;
export default function PrivacyPolicyPage(){return <main id="main-content"><PageHero eyebrow="Privacy" title="Process the content. Return the result. Minimize what remains." copy="Privacy claims belong beside the actions they describe, and the policy should match runtime behavior. This page describes the intended content boundary for the current service." aside="Free inspection is local-first. Billable server processing is intentionally ephemeral. Operational history excludes submitted content and filenames."/><section className="shell legal-grid">{SECTIONS.map(([title,copy],index)=><article className="legal-card" key={title}><span className="mono-label">{String(index+1).padStart(2,"0")}</span><h2>{title}</h2><p>{copy}</p></article>)}</section><p className="shell legal-review-note">This policy should receive legal review before live-money public availability.</p></main>}
