-- The original Phase 6 draft was retired because its refund calculation was not true FIFO
-- and its auth.users ON DELETE CASCADE relationships conflicted with the append-only ledger.
--
-- Canonical Phase 6 is now the versioned migration:
--   supabase/migrations/20260901184500_phase6_fifo_privacy.sql
--
-- Do not apply an unversioned copy of Phase 6. Validate the canonical migration on a
-- Supabase development branch, run its schema/security/readiness tests, then apply the
-- exact migration through Supabase migration tooling so production migration history is real.
