"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { CREDIT_PACKS, type CreditPackId } from "@/lib/billing/catalog";
import styles from "./account-bar.module.css";
interface IdentityState { userId: string; isAnonymous: boolean; } interface BalanceState { settled: number; held: number; available: number; }
export function AccountBar() {
  const supabase = useMemo(() => { try { return createClient(); } catch { return null; } }, []); const [identity,setIdentity]=useState<IdentityState|null>(null); const [balance,setBalance]=useState<BalanceState|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
  const refresh=useCallback(async()=>{ if(!supabase)return; const {data}=await supabase.auth.getClaims(); const claims=data?.claims as Record<string,unknown>|undefined; if(!claims||typeof claims.sub!=="string"){setIdentity(null);setBalance(null);return;} setIdentity({userId:claims.sub,isAnonymous:claims.is_anonymous===true||claims.is_anonymous==="true"}); const response=await fetch("/api/billing/balance",{cache:"no-store"}); if(response.ok){const payload=await response.json();setBalance(payload.balance);} },[supabase]);
  useEffect(()=>{void refresh();},[refresh]);
  async function startGuest(){setBusy(true);setMessage(null);try{const response=await fetch("/api/auth/anonymous",{method:"POST"});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Could not start a guest session.");await refresh();}catch(error){setMessage(error instanceof Error?error.message:"Could not start a guest session.");}finally{setBusy(false);}}
  async function google(){if(!supabase)return;setBusy(true);setMessage(null);const redirectTo=`${window.location.origin}/auth/callback?next=/`;const result=identity?.isAnonymous?await supabase.auth.linkIdentity({provider:"google",options:{redirectTo}}):await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo}});if(result.error){setMessage(result.error.message);setBusy(false);}}
  async function signOut(){setBusy(true);await fetch("/api/auth/signout",{method:"POST"});setIdentity(null);setBalance(null);setBusy(false);}
  async function buy(packId:CreditPackId){setBusy(true);setMessage(null);try{const response=await fetch("/api/billing/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({packId})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Checkout is not available.");window.location.assign(payload.url);}catch(error){setMessage(error instanceof Error?error.message:"Checkout is not available.");setBusy(false);}}
  return <section className={styles.bar} aria-label="Account and credits"><div><p className={styles.eyebrow}>Account · Phase 4</p><strong>{identity?(identity.isAnonymous?"Guest session":"Signed-in account"):"No account yet"}</strong><span className={styles.subtext}>{balance?`${balance.available} available credit${balance.available===1?"":"s"}${balance.held?` · ${balance.held} held`:""}`:"Create a guest session to use metered editing."}</span></div><div className={styles.actions}>{!identity&&<button disabled={busy||!supabase} onClick={startGuest}>Start guest</button>}{(!identity||identity.isAnonymous)&&<button disabled={busy||!supabase} onClick={google}>{identity?"Upgrade with Google":"Sign in with Google"}</button>}{identity&&Object.values(CREDIT_PACKS).map(pack=><button className={styles.pack} disabled={busy} key={pack.id} onClick={()=>buy(pack.id)}>+{pack.credits}</button>)}{identity&&<button className={styles.secondary} disabled={busy} onClick={signOut}>Sign out</button>}</div>{message&&<p className={styles.message}>{message}</p>}</section>;
}
