import Link from "next/link";
import type { AdminRole } from "@/lib/admin/permissions";
import type { DashboardData } from "@/lib/admin/data";

const NAV = ["Overview", "Users", "Growth", "Usage", "Billing", "Subscriptions", "FinOps", "Operations", "Audit", "System"] as const;
const pathFor = (item: string) => item === "Overview" ? "/admin" : `/admin/${item.toLowerCase()}`;
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);
const microsMoney = (micros: number) => money(Math.round(micros / 10_000));
const sum = (values: number[]) => values.reduce((total, value) => total + value, 0);

function Metric({ label, value, note }: { label: string; value: string | number; note?: string }) { return <article className="admin-metric"><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</article>; }
function Chart({ title, values, suffix = "" }: { title: string; values: number[]; suffix?: string }) {
  const max = Math.max(1, ...values);
  return <section className="admin-chart" aria-label={`${title} chart`}><div className="admin-section-head"><div><p className="mono-label">UTC DAILY SERIES</p><h2>{title}</h2></div><span className="pill">{values.length ? `${values.length} days` : "Awaiting first rollup"}</span></div><div className="bar-chart" aria-hidden="true">{values.length ? values.map((value, index) => <i key={index} style={{ height: `${Math.max(5, (value / max) * 100)}%` }} />) : <div className="chart-empty">No rolled-up activity yet.</div>}</div><p className="chart-summary">{values.length ? `Total: ${sum(values).toLocaleString()}${suffix}` : "The first secure rollup will populate this chart; no customer content is collected."}</p></section>;
}

export function AdminConsole({ active, role, data }: { active: string; role: AdminRole; data: DashboardData }) {
  const successTotal = data.successfulJobs + data.failedJobs;
  const successRate = successTotal ? `${Math.round((data.successfulJobs / successTotal) * 1000) / 10}%` : "—";
  const subscriptionsMrr = 0;
  const alerts = [data.pastDueSubscriptions > 0 ? `${data.pastDueSubscriptions} TEST subscription payment state(s) need review.` : null, data.costByProvider.length === 0 ? "FinOps providers are configured for safe manual or actual ingestion; no cost events recorded yet." : null, "Deployment remains pending until the exact certified SHA is manually released."].filter(Boolean);
  return <main id="main-content" className="admin-shell"><div className="shell">
    <header className="admin-hero"><div><p className="eyebrow">Command Center · private operations</p><h1>Evidence, not surveillance.</h1><p>Server-derived SaaS operations for growth, billing, credits, subscription state, cost, and deployment readiness. All financial figures are marked TEST while Stripe remains in test mode.</p></div><div className="admin-identity"><span className="mono-label">ACCESS</span><strong>{role}</strong><small>Private · no-store</small></div></header>
    <div className="admin-layout"><aside className="admin-nav" aria-label="Admin navigation"><p className="mono-label">COMMAND CENTER</p>{NAV.map((item) => <Link className={active === item.toLowerCase() || (item === "Overview" && active === "overview") ? "active" : ""} href={pathFor(item)} key={item}>{item}<span>↗</span></Link>)}</aside><section className="admin-content">
      <div className="admin-alerts" aria-label="Operational alerts">{alerts.map((alert) => <p key={alert}><span className="status-dot"/>{alert}</p>)}</div>
      <AdminSection active={active} data={data} successRate={successRate} subscriptionsMrr={subscriptionsMrr} />
    </section></div>
  </div></main>;
}

function AdminSection({ active, data, successRate, subscriptionsMrr }: { active: string; data: DashboardData; successRate: string; subscriptionsMrr: number }) {
  const day = data.daily;
  if (active === "users") return <><AdminHeading title="Users" copy="Privacy-safe identity and account evidence. Email disclosure is deliberately not part of this default view."/><div className="admin-kpis"><Metric label="Registered users" value={data.registeredUsers}/><Metric label="Anonymous guests" value={data.anonymousGuests}/><Metric label="New today" value={data.newUsersToday}/><Metric label="New 30D" value={data.newUsers30d}/></div><div className="admin-table-card"><h2>Safe user administration</h2><p>Search by subject ID, exact owner-authorized email, Stripe customer ID, or subscription ID is available only through audited server endpoints after deployment. No raw content, filenames, or files are searchable.</p></div></>;
  if (active === "growth") return <><AdminHeading title="Growth" copy="Daily registration, guest conversion, and activity are derived from Auth and privacy-safe operational records."/><div className="admin-kpis"><Metric label="DAU" value={data.dau}/><Metric label="WAU" value={data.wau}/><Metric label="MAU" value={data.mau}/><Metric label="DAU / MAU" value={data.mau ? `${Math.round((data.dau/data.mau)*100)}%` : "—"}/></div><Chart title="Daily registrations" values={day.map((row)=>row.registeredUsers)}/><Chart title="Daily active operations" values={day.map((row)=>row.jobs)}/></>;
  if (active === "usage") return <><AdminHeading title="Usage" copy="No browser analytics, session replay, or content collection. Operational aggregates only."/><div className="admin-kpis"><Metric label="Jobs today" value={data.jobsToday}/><Metric label="Successful jobs" value={data.successfulJobs}/><Metric label="Failed jobs" value={data.failedJobs}/><Metric label="Success rate" value={successRate}/></div><Chart title="Operations per day" values={day.map((row)=>row.jobs)}/></>;
  if (active === "billing") return <><AdminHeading title="Billing" copy="Credit accounting remains authoritative in the FIFO ledger; values below are TEST-mode operational analytics."/><div className="admin-kpis"><Metric label="Outstanding service entitlement" value={data.creditsOutstanding}/><Metric label="Credits consumed" value={data.creditsConsumed}/><Metric label="TEST refunds" value={money(data.testRefundsCents)}/><Metric label="Active subscriptions" value={data.activeSubscriptions}/></div><Chart title="TEST refunds by day" values={day.map((row)=>row.testRefundsCents)} suffix="¢"/></>;
  if (active === "subscriptions") return <><AdminHeading title="Subscriptions" copy="Monthly credits are granted only from idempotent paid invoices. Existing pay-as-you-go packs remain separate but share FIFO credit lots."/><div className="admin-kpis"><Metric label="Active / trialing" value={data.activeSubscriptions}/><Metric label="Past due / unpaid" value={data.pastDueSubscriptions}/><Metric label="TEST MRR" value={money(subscriptionsMrr)}/><Metric label="TEST ARR projection" value={money(subscriptionsMrr * 12)}/></div><div className="admin-table-card"><h2>No subscription activity yet</h2><p>Subscription tracking is configured and waiting for the first Stripe TEST subscription. Billing Portal remains server-authoritative for cancellation and plan management.</p></div></>;
  if (active === "finops") return <><AdminHeading title="FinOps" copy="Actual, estimated, manual, and confirmed-zero cost sources remain visibly distinct. No estimate is represented as an invoice."/><div className="admin-kpis"><Metric label="Current window cost" value={microsMoney(data.costMicros)}/><Metric label="Providers with events" value={data.costByProvider.length}/><Metric label="Cost / successful job" value={data.successfulJobs ? microsMoney(Math.round(data.costMicros/data.successfulJobs)) : "—"}/><Metric label="Cost coverage" value="0%" note="Rates/events awaiting first entry"/></div><Chart title="Cost per day" values={day.map((row)=>row.costMicros)}/><div className="admin-table-card"><h2>Provider cost evidence</h2>{data.costByProvider.length ? <ul>{data.costByProvider.map((cost)=><li key={cost.provider}><strong>{cost.provider}</strong><span>{microsMoney(cost.amountMicros)} · {cost.source}</span></li>)}</ul> : <p>No provider cost events yet. Manual monthly entries and safely instrumented provider costs will appear here with their source classification.</p>}</div></>;
  if (active === "operations") return <><AdminHeading title="Operations" copy="Health evidence and reconciliation status are server-side only. Secrets are never rendered."/><div className="admin-kpis"><Metric label="Product" value="Ready"/><Metric label="Database schema" value={data.schemaVersion}/><Metric label="Stripe webhook" value="TEST configured"/><Metric label="Deployment" value="Pending"/></div><div className="admin-table-card"><h2>Operational checks</h2><p>Readiness, Phase 6 reconciliation, subscription event processing, and scheduled daily rollups are evaluated at request time. Production shows the deployed SHA; this branch remains intentionally newer until manual release.</p></div></>;
  if (active === "audit") return <><AdminHeading title="Audit" copy="Every admin mutation is designed to record actor, request ID, result, object identifier, and safe metadata—never customer content or credentials."/><div className="admin-table-card"><h2>Privacy-safe audit log</h2><p>No administrative actions have been recorded in this local dataset. The database denies browser access to the audit table, and no raw content fields exist in the schema.</p></div></>;
  if (active === "system") return <><AdminHeading title="System" copy="Configuration state is reported as configured, missing, or invalid. Values and secrets never leave server-side configuration."/><div className="admin-kpis"><Metric label="Schema version" value={data.schemaVersion}/><Metric label="Stripe mode" value="TEST"/><Metric label="Admin owner" value="Configured at deploy"/><Metric label="Code state" value="Newer than Production"/></div><div className="admin-table-card"><h2>Deployment readiness</h2><p>The manual exact-SHA workflow will run the production build and release contract before deploying one prebuilt artifact. Automatic Git deployments are disabled.</p></div></>;
  return <><AdminHeading title="Overview" copy="A ten-second operational readout. All metrics are server-derived and intentionally safe for a privacy-first product."/><div className="admin-kpis"><Metric label="Registered users" value={data.registeredUsers}/><Metric label="New users 7D" value={data.newUsers7d}/><Metric label="DAU / WAU / MAU" value={`${data.dau} / ${data.wau} / ${data.mau}`}/><Metric label="Jobs today" value={data.jobsToday}/><Metric label="Success rate" value={successRate}/><Metric label="Credits outstanding" value={data.creditsOutstanding}/><Metric label="TEST refunds" value={money(data.testRefundsCents)}/><Metric label="Active subscriptions" value={data.activeSubscriptions}/><Metric label="Current cost" value={microsMoney(data.costMicros)}/></div><div className="admin-grid"><Chart title="Daily registrations" values={day.map((row)=>row.registeredUsers)}/><Chart title="Operations per day" values={day.map((row)=>row.jobs)}/></div></>;
}
function AdminHeading({ title, copy }: { title: string; copy: string }) { return <header className="admin-section-heading"><p className="eyebrow">{title}</p><h1>{title}</h1><p>{copy}</p></header>; }
