import Link from "next/link";
import type { AdminRole } from "@/lib/admin/permissions";
import type { DashboardData } from "@/lib/admin/data";

const NAV=["Overview","Users","Growth","Usage","Billing","Subscriptions","FinOps","Operations","Audit","System"] as const;
const pathFor=(item:string)=>item==="Overview"?"/admin":`/admin/${item.toLowerCase()}`;
const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);
const microsMoney=(micros:number)=>money(Math.round(micros/10_000));
const sum=(values:number[])=>values.reduce((total,value)=>total+value,0);

function Metric({label,value,note}:{label:string;value:string|number;note?:string}){return <article className="admin-metric"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</article>;}
function Chart({title,values,suffix=""}:{title:string;values:number[];suffix?:string}){
  const max=Math.max(1,...values);
  return <section className="admin-chart" aria-label={`${title} chart`}><div className="admin-section-head"><div><p className="mono-label">UTC DAILY SERIES</p><h2>{title}</h2></div><span className="pill">{values.length?`${values.length} days`:"Awaiting first rollup"}</span></div><div className="bar-chart" aria-hidden="true">{values.length?values.map((value,index)=><i key={index} style={{height:`${Math.max(5,(value/max)*100)}%`}}/>):<div className="chart-empty">No rolled-up activity yet.</div>}</div><p className="chart-summary">{values.length?`Total: ${sum(values).toLocaleString()}${suffix}`:"The first secure rollup will populate this chart; no customer content is collected."}</p></section>;
}

export function AdminConsole({active,role,data}:{active:string;role:AdminRole;data:DashboardData}){
  const successTotal=data.successfulJobs+data.failedJobs;
  const successRate=successTotal?`${Math.round((data.successfulJobs/successTotal)*1000)/10}%`:"—";
  const netRevenue=data.testGrossRevenueCents-data.testRefundsCents;
  const contributionCents=netRevenue-Math.round(data.costMicros/10_000);
  const contributionMargin=netRevenue>0?`${Math.round((contributionCents/netRevenue)*1000)/10}%`:"—";
  const alerts=[
    data.pastDueSubscriptions>0?`${data.pastDueSubscriptions} TEST subscription payment state(s) need review.`:null,
    data.costByProvider.length===0?"No provider cost events have been recorded yet; FinOps will remain explicit about missing evidence.":null,
  ].filter((value):value is string=>Boolean(value));
  return <main id="main-content" className="admin-shell"><div className="shell">
    <header className="admin-hero"><div><p className="eyebrow">Command Center · private operations</p><h1>Evidence, not surveillance.</h1><p>Server-derived SaaS operations for growth, billing, credits, subscription state, cost, and deployment readiness. All financial figures are marked TEST while Stripe remains in test mode.</p></div><div className="admin-identity"><span className="mono-label">ACCESS</span><strong>{role}</strong><small>Private · no-store</small></div></header>
    <div className="admin-layout"><aside className="admin-nav" aria-label="Admin navigation"><p className="mono-label">COMMAND CENTER</p>{NAV.map((item)=><Link className={active===item.toLowerCase()||(item==="Overview"&&active==="overview")?"active":""} href={pathFor(item)} key={item}>{item}<span>↗</span></Link>)}</aside><section className="admin-content">
      {alerts.length>0&&<div className="admin-alerts" aria-label="Operational alerts">{alerts.map((alert)=><p key={alert}><span className="status-dot"/>{alert}</p>)}</div>}
      <AdminSection active={active} data={data} successRate={successRate} netRevenue={netRevenue} contributionMargin={contributionMargin}/>
    </section></div>
  </div></main>;
}

function AdminSection({active,data,successRate,netRevenue,contributionMargin}:{active:string;data:DashboardData;successRate:string;netRevenue:number;contributionMargin:string}){
  const day=data.daily;
  if(active==="users")return <><AdminHeading title="Users" copy="Privacy-safe identity and account evidence. Email disclosure is deliberately not part of this default view."/><div className="admin-kpis"><Metric label="Registered users" value={data.registeredUsers}/><Metric label="Anonymous guests" value={data.anonymousGuests}/><Metric label="New today" value={data.newUsersToday}/><Metric label="New 30D" value={data.newUsers30d}/></div><div className="admin-table-card"><h2>Safe user administration</h2><p>Identity counts are server-derived from Supabase Auth. Raw customer content, filenames, and files are never part of this operational view.</p></div></>;
  if(active==="growth")return <><AdminHeading title="Growth" copy="Daily registration, guest conversion, and activity are derived from Auth and privacy-safe operational records."/><div className="admin-kpis"><Metric label="DAU" value={data.dau}/><Metric label="WAU" value={data.wau}/><Metric label="MAU" value={data.mau}/><Metric label="DAU / MAU" value={data.mau?`${Math.round((data.dau/data.mau)*100)}%`:"—"}/></div><Chart title="Daily registrations" values={day.map((row)=>row.registeredUsers)}/><Chart title="Daily active operations" values={day.map((row)=>row.jobs)}/></>;
  if(active==="usage")return <><AdminHeading title="Usage" copy="No browser analytics, session replay, or content collection. Operational aggregates only."/><div className="admin-kpis"><Metric label="Jobs today" value={data.jobsToday}/><Metric label="Successful jobs" value={data.successfulJobs}/><Metric label="Failed jobs" value={data.failedJobs}/><Metric label="Success rate" value={successRate}/></div><Chart title="Operations per day" values={day.map((row)=>row.jobs)}/></>;
  if(active==="billing")return <><AdminHeading title="Billing" copy="Credit accounting remains authoritative in the FIFO ledger; financial values are Stripe TEST operational evidence."/><div className="admin-kpis"><Metric label="TEST gross revenue" value={money(data.testGrossRevenueCents)}/><Metric label="TEST refunds" value={money(data.testRefundsCents)}/><Metric label="TEST net revenue" value={money(netRevenue)}/><Metric label="Outstanding entitlement" value={data.creditsOutstanding}/><Metric label="Credits consumed" value={data.creditsConsumed}/><Metric label="Active subscriptions" value={data.activeSubscriptions}/></div><Chart title="TEST gross revenue by day" values={day.map((row)=>row.testGrossRevenueCents)} suffix="¢"/><Chart title="TEST refunds by day" values={day.map((row)=>row.testRefundsCents)} suffix="¢"/></>;
  if(active==="subscriptions")return <><AdminHeading title="Subscriptions" copy="Monthly credits are granted only from idempotent paid invoices. Existing pay-as-you-go packs remain separate but share FIFO credit lots."/><div className="admin-kpis"><Metric label="Active / trialing" value={data.activeSubscriptions}/><Metric label="Past due / unpaid" value={data.pastDueSubscriptions}/><Metric label="TEST MRR" value={money(data.testMrrCents)}/><Metric label="TEST ARR projection" value={money(data.testMrrCents*12)}/></div><div className="admin-table-card"><h2>{data.activeSubscriptions?"Subscription portfolio active":"No subscription activity yet"}</h2><p>{data.activeSubscriptions?"Current TEST MRR is derived from authoritative active/trialing subscription plan records. Invoice-paid grants remain idempotent by Stripe invoice ID.":"Subscription tracking is ready for the first Stripe TEST subscription. Billing Portal remains server-authoritative for cancellation."}</p></div></>;
  if(active==="finops")return <><AdminHeading title="FinOps" copy="Actual, estimated, manual, and confirmed-zero cost sources remain visibly distinct. No estimate is represented as an invoice."/><div className="admin-kpis"><Metric label="Current window cost" value={microsMoney(data.costMicros)}/><Metric label="TEST net revenue" value={money(netRevenue)}/><Metric label="Contribution margin" value={contributionMargin}/><Metric label="Cost / successful job" value={data.successfulJobs?microsMoney(Math.round(data.costMicros/data.successfulJobs)):"—"}/><Metric label="Providers with cost evidence" value={data.costByProvider.length}/></div><Chart title="Cost per day" values={day.map((row)=>row.costMicros)}/><div className="admin-table-card"><h2>Provider cost evidence</h2>{data.costByProvider.length?<ul>{data.costByProvider.map((cost)=><li key={cost.provider}><strong>{cost.provider}</strong><span>{microsMoney(cost.amountMicros)} · {cost.source}</span></li>)}</ul>:<p>No provider cost events yet. The console reports the absence explicitly rather than inventing cost coverage.</p>}</div></>;
  if(active==="operations")return <><AdminHeading title="Operations" copy="Health evidence and reconciliation status are server-side only. Secrets are never rendered."/><div className="admin-kpis"><Metric label="Database schema" value={data.schemaVersion}/><Metric label="Stripe mode" value="TEST"/><Metric label="Metrics generated" value={new Date(data.generatedAt).toLocaleString("en-US",{timeZone:"UTC"})+" UTC"}/></div><div className="admin-table-card"><h2>Runtime certification</h2><p>Deployment SHA and complete dependency readiness are authoritative at <code>/api/health</code> and <code>/api/readiness</code>. Scheduled reconciliation and daily rollups use server-only credentials.</p></div></>;
  if(active==="audit")return <><AdminHeading title="Audit" copy="Admin mutations record actor, request ID, result, object identifier, and safe metadata—never customer content or credentials."/><div className="admin-table-card"><h2>Privacy-safe audit log</h2><p>The database denies browser access to private audit tables, and the schema contains no raw content fields.</p></div></>;
  if(active==="system")return <><AdminHeading title="System" copy="Configuration values and secrets stay server-side. Runtime readiness is exposed only as safe configured/missing status."/><div className="admin-kpis"><Metric label="Schema version" value={data.schemaVersion}/><Metric label="Stripe mode" value="TEST"/><Metric label="Admin authorization" value="Server-side"/><Metric label="Automatic Git deploys" value="Disabled"/></div><div className="admin-table-card"><h2>Release evidence</h2><p>Use <code>/api/health</code> for the exact deployed SHA and <code>/api/readiness</code> for database and configuration readiness. The release workflow refuses deployment when Production preflight fails.</p></div></>;
  return <><AdminHeading title="Overview" copy="A ten-second operational readout. All metrics are server-derived and intentionally safe for a privacy-first product."/><div className="admin-kpis"><Metric label="Registered users" value={data.registeredUsers}/><Metric label="New users 7D" value={data.newUsers7d}/><Metric label="DAU / WAU / MAU" value={`${data.dau} / ${data.wau} / ${data.mau}`}/><Metric label="Jobs today" value={data.jobsToday}/><Metric label="Success rate" value={successRate}/><Metric label="Credits outstanding" value={data.creditsOutstanding}/><Metric label="TEST gross revenue" value={money(data.testGrossRevenueCents)}/><Metric label="TEST net revenue" value={money(netRevenue)}/><Metric label="TEST MRR" value={money(data.testMrrCents)}/><Metric label="Active subscriptions" value={data.activeSubscriptions}/><Metric label="Current cost" value={microsMoney(data.costMicros)}/><Metric label="Contribution margin" value={contributionMargin}/></div><div className="admin-grid"><Chart title="Daily registrations" values={day.map((row)=>row.registeredUsers)}/><Chart title="Operations per day" values={day.map((row)=>row.jobs)}/></div></>;
}
function AdminHeading({title,copy}:{title:string;copy:string}){return <header className="admin-section-heading"><p className="eyebrow">{title}</p><h1>{title}</h1><p>{copy}</p></header>;}
