import { PageHero } from "@/components/quiet-forensics";
const TERMS=[
["Credits","Scanning and inspection are free. Billable text uses one credit per 1,000 source words rounded up; supported DOCX/PNG/JPEG sanitation uses a flat one-credit rule within the file limit. Failed reserved operations release their holds instead of committing a successful debit."],
["Purchases","Credit packs are one-time purchases rather than subscriptions. The current service uses Stripe TEST mode only and does not accept live money. The implemented Checkout contract is restricted to United States addresses."],
["Refunds","Signed-in users may request refunds for eligible unused purchased credits within the configured refund window when authoritative billing history supports the quote. Stripe remains the payment authority; a browser-side balance change is never treated as a refund."],
["Acceptable use","Do not use the service to misrepresent authorship, evade lawful controls, infringe rights, remove provenance deceptively, or process content you are not authorized to handle. Semantic editing is not guaranteed to defeat AI detectors or prove human authorship."],
["Account deletion","Deletion removes the authentication identity only when backend readiness confirms the accounting system can detach that identity while preserving narrowly required reconciliation and anti-abuse records."],
] as const;
export default function TermsPage(){return <main id="main-content"><PageHero eyebrow="Terms" title="Clear rules for an evidence-first service." copy="The service separates free inspection, billable actions, test-mode payments, refunds, and identity controls so users can see the difference between an operation and a claim." aside="Stripe is TEST mode only in the current service. No live payment should be interpreted as available."/><section className="shell legal-grid">{TERMS.map(([title,copy],index)=><article className="legal-card" key={title}><span className="mono-label">{String(index+1).padStart(2,"0")}</span><h2>{title}</h2><p>{copy}</p></article>)}</section><p className="shell legal-review-note">These terms should receive legal review before live-money public availability.</p></main>}
